version: '3.7'
services:
  skyscrapper:
    build:
      context: .
      dockerfile: docker/nodejs/Dockerfile
    image: skyscrapper
    container_name: sky-scrapper
    hostname: sky-scrapper
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      PORT: 3000
      TZ: ${TZ} # TIME ZONE PROPERTIES
      JWT_TOKEN: ${JWT_TOKEN} # JWT TOKEN
      MONGO_USERNAME: ${MONGO_USERNAME} # MONGODB PROPERTIES
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_DATABASE: ${MONGO_DATABASE}
      MONGO_HOST: ${MONGO_HOST}
      EMAIL_HOST: ${EMAIL_HOST} #EMAIL PROPERTIES
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_USERNAME: ${EMAIL_USERNAME}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      STATIC_SERVER_PATH: ${STATIC_SERVER_PATH} # STATIC SERVER FOR PROFILE PHOTO
      IS_PRODUCTION: ${IS_PRODUCTION}
      PUBLIC_KEY: ${PUBLIC_KEY} # WEB PUSH PROPERTIES
      PRIVATE_KEY: ${PRIVATE_KEY}
      EMAIL_WEB_PUSH: ${EMAIL_WEB_PUSH}
      RP_ID: ${RP_ID} # WEB AUTH PROPERTIES
      RP_ID_ARRAY: ${RP_ID_ARRAY}
      ORIGIN: ${ORIGIN}
      LOGO_APP: ${LOGO_APP}
      LOGO_ICON: ${LOGO_ICON}
      URL_WEB: ${URL_WEB}
      DATE_PATTERN: ${DATE_PATTERN} # LOGGER PROPERTIES
      APP_NAME: ${APP_NAME}
      MAX_SIZE: ${MAX_SIZE}
      MAX_DAYS: ${MAX_DAYS}
      LOG_FOLDER: ${LOG_FOLDER}
      TIMESTAMP_FORMAT: ${TIMESTAMP_FORMAT}